apiVersion: v1
kind: Service
metadata:
  name: argoplay-service
spec:
  selector:
    app: argoplay-app
  ports:
    - protocol: TCP
      port: 8427
      targetPort: 8080
      name: argoplayport
  type: LoadBalancer
