apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoplay-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/223311/argo-play.git
    targetRevision: HEAD
    path: k8/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argoplay-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false