apiVersion: batch/v1
kind: Job
metadata:
  name: springboot
  generateName: springboot
  annotations:
    argocd.argoproj.io/hook: PostSync,Sync,PreSync,SyncFail
spec:
  template:
    spec:
      containers:
        - name: teamnotification
          image: sankar31/baseimg:1.0
          command:
            - 'curl args:  -X POST -H ''Content-type: application/json'' --data ''{"@type":"MessageCard","@context":"http://schema.org/extensions","themeColor":"DD5235","summary":"Build Failed..","sections":[{"activityTitle":"![TestImage](https://avatars2.githubusercontent.com/u/2181346?s=50&v=4)Build Failed..","activitySubtitle":"On Project Test","activityImage":"https://avatars2.githubusercontent.com/u/2181346?s=200&v=4","facts":[{"name":"Assigned to","value":"Drone CI"}],"markdown":true}],"potentialAction":[{"@type":"ActionCard","name":"Add a comment","inputs":[{"@type":"TextInput","id":"comment","isMultiline":false,"title":"Add a comment here for this task"}],"actions":[{"@type":"HttpPOST","name":"Add comment","target":"http://..."}]},{"@type":"ActionCard","name":"Change status","inputs":[{"@type":"MultichoiceInput","id":"list","title":"Select a status","isMultiSelect":"false","choices":[{"display":"In Progress","value":"1"},{"display":"Active","value":"2"},{"display":"Closed","value":"3"}]}],"actions":[{"@type":"HttpPOST","name":"Save","target":"http://..."}]}]}'' https://outlook.office.com/'
      restartPolicy: Never
  backoffLimit: 2
