apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoplay-deploy
  labels:
    app: argoplay-app
  annotations:
spec:
  selector:
    matchLabels:
      app: argoplay-app
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: argoplay-app
    spec:
      containers:
      - name: argoplay-app
        image: sankar31/droneex:126
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "999Mi"
            cpu: "999m"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: mysecret
      - name: config-volume
        configMap:
          name: example-config #name of our configmap object
